name: sql_builder_dart
description: "Build a SQL with strong-typed function"
version: 1.0.0+1
homepage: https://github.com/wahderland/sql_builder_dart

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies:
  tuple: ^2.0.0
